swagger: "2.0"
info:
  version: 1.0.0
  title: Common Geo-Registry REST API
  license:
    name: MIT
host: yourdomain
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /geoobject:
    get:
      summary: Get a GeoObject by id.
      operationId: getGeoObject
      tags:
        - GeoObject
      parameters:
        - name: uid
          in: query
          description: GeoObject
          required: true
          type: string
      responses:
        "200":
          description: A GeoObject
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/GeoObject'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a GeoObject
      operationId: createGeoObject
      tags:
        - GeoObject
      parameters:
        - name: geoObject
          in: body
          description: GeoObject
          required: true
          schema:
            $ref: '#/definitions/GeoObject'
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update a GeoObject
      operationId: updateGeoObject
      tags:
        - GeoObject
      parameters:
        - name: geoObject
          in: body
          description: GeoObject
          required: true
          schema:
            $ref: '#/definitions/GeoObject'
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /childgeoobjects:
    get:
      summary: Get all direct child GeoObjects of a specific GeoObject.
      operationId: getChildGeoObjects
      tags:
        - GeoObject
      parameters:
        - name: parentUid
          in: query
          description: GeoObject
          required: true
          type: string
        - name: childrenTypes
          in: body
          description: Children types.
          required: true
          schema:
            type: array
            items:
              type: string
        - name: recursive
          in: query
          description: Recursive.
          required: true
          type: string
      responses:
        "200":
          description: A GeoObject
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/GeoObject'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /parentgeoobjects:
    get:
      summary: Get all direct parent GeoObjects of a specific GeoObject.
      operationId: getParentGeoObjects
      tags:
        - GeoObject
      parameters:
        - name: childUid
          in: query
          description: GeoObject
          required: true
          type: string
        - name: parentTypes
          in: body
          description: Parent types.
          required: true
          schema:
            type: array
            items:
              type: string
        - name: recursive
          in: query
          description: Recursive.
          required: true
          type: string
      responses:
        "200":
          description: A GeoObject
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/GeoObject'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /geoobjectuids:
    get:
      summary: 	Get list of valid UIDs.
      operationId: getGeoObjectUids
      tags:
        - GeoObject
      parameters:
        - name: numberOfUids
          in: query
          description: Number of UIDs to return.
          required: true
          type: integer
      responses:
        "200":
          description: A list of UIDs that can be used to create new GeoObjects on the client.
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema: 
            type: array
            items: 
              type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /geoobjecttypes:
    get:
      summary: 	Get list of valid UIDs.
      operationId: getGeoObjectTypes
      tags:
        - GeoObject
      parameters:
        - name: types
          in: query
          description: Get list of valid GeoObject types.
          required: true
          type: array
          items:
            type: string
      responses:
        "200":
          description: A list of UIDs that can be used to create new GeoObjects on the client.
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema: 
            type: array
            items: 
              type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
definitions:
  GeoObject:
    $ref: "#/definitions/Feature"
    
  GeoObjects:
    type: array
    items:
      $ref: '#/definitions/GeoObject'
      
  GeoObjectType:
    type: object
    properties:
      code: 
        type: string
      localizedLabel: 
        type: string
      localizedDescription: 
        type: string
      attributes: 
        type: array
        items:
          $ref: '#/definitions/AttributeType'
    
  AttributeType:
    type: object
    properties:
      code: 
        type: string
      localizedLabel: 
        type: string
      type: 
        type: string
 
  AttributeTypes:
    type: array
    items:
      $ref: '#/definitions/AttributeType'
  
  Term:
    type: object
    properties:
      code:
        type: string
      localizedLabel:
        type: string
      children:
        type: array
        items:
          $ref: '#/definitions/Term' # Swagger UI can't render circular references

  Geometry:
    type: object
    description: GeoJSon geometry
    discriminator: type
    required:
      - type
    externalDocs:
      url: http://geojson.org/geojson-spec.html#geometry-objects
    properties:
      type:
        type: string
        enum:
        - Point
        - LineString
        - Polygon
        - MultiPoint
        - MultiLineString
        - MultiPolygon
        description: the geometry type
    
  Point3D:
    type: array
    description: Point in 3D space
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id2
    minItems: 2
    maxItems: 3
    items:
      type: number
          
  Point:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id2
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            $ref: '#/definitions/Point3D'
            
  LineString:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id3
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              $ref: '#/definitions/Point3D'

  Polygon:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id4
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              type: array
              items:
                $ref: '#/definitions/Point3D'

  MultiPoint:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id5
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              $ref: '#/definitions/Point3D'

  MultiLineString:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id6
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              type: array
              items:
                $ref: '#/definitions/Point3D'

  MultiPolygon:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id6
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              type: array
              items:
                type: array
                items:
                  $ref: '#/definitions/Point3D'

  GeometryCollection:
    type: object
    description: GeoJSon geometry collection
    required:
     - type
     - geometries
    externalDocs:
      url: http://geojson.org/geojson-spec.html#geometrycollection
    properties:
      type:
        type: string
        enum:
        - GeometryCollection
      geometries:
        type: array
        items:
          $ref: '#/definitions/Geometry'

  Feature:
    type: object
    description: GeoJSon Feature
    required:
     - type
     - id
     - geometry
    externalDocs:
      url: https://tools.ietf.org/html/rfc7946#section-3.2
    properties:
      type:
        type: string
        enum:
          - Feature
      id:
        type: integer
      geometry:
        $ref: '#/definitions/GeometryCollection'
      properties:
        type: object
        properties:
          uid: 
            type: string
          code: 
            type: string
          type: 
            $ref: '#/definitions/GeoObjectType'
          status: 
            $ref: '#/definitions/Term'

  FeatureCollection:
    type: object
    description: GeoJSon Feature collection
    required:
     - type
     - features
    externalDocs:
      url: https://tools.ietf.org/html/rfc7946#section-3.3
    properties:
      type:
        type: string
        enum:
        - FeatureCollection
      features:
        type: array
        items:
          $ref: '#/definitions/Feature'
             
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
